apiVersion: v1
kind: Service
metadata:
  name: azure
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: azure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure
  labels:
    app: azure
spec:
  selector:
    matchLabels:
      app: azure 
  template:
    metadata:
      labels:
        app: azure
    spec:
      containers:
      - image: azure/azure:latest
        name: image
        args:
        - server
        - /data
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: objectstorage-provisioner
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: objectstorage-provisioner
              key: SECRET_KEY