---
kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: cosi-driver-test-acc
  labels:
    app.kubernetes.io/part-of: cosi-driver-test
    app.kubernetes.io/name: cosi-driver-test
driverName: blob.cosi.azure.com
deletionPolicy: Delete
parameters: 
  bucketunittype: storageaccount
  storageaccountname: cositestacc
  resourcegroup: cosi-test
  region: eastus