name: MacOS Build & Unit Tests
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: check out code in the Go module directory
      uses: actions/checkout@v3

    - name: Build Test
      run: |
        go test -covermode=count -coverprofile=profile.cov ./pkg/...